[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scribe"
version = "0.3.0"
description = "scribe is a local speech recognition tool that provides real-time transcription using vosk and whisper AI."
authors = [
    { name="Mahé Perrette", email="mahe.perrette@gmail.com" }
]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "sounddevice",
    "tqdm",
    "requests",
]
optional-dependencies = { keyboard = ["pynput"], whisper = ["openai-whisper"], vosk = ["vosk"], all = ["pynput", "openai-whisper", "vosk"] }

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: MIT License",
    "Operating System :: OS Independent",
]

keywords = [
    "speech recognition",
    "transcription",
    "AI",
    "language",
    "vosk",
    "whisper",
    "openai",
]

[tool.setuptools]
packages = [ "scribe" ]

[project.urls]
Homepage = "https://github.com/scribe"

[project.scripts]
scribe = "scribe.streamer:main"
scribe-install = "scribe.install_desktop:main"
